{
    'name': 'Guía remisión Solyman',
    'version': '18.0.0.0',
    'summary': 'Guía remisión Perú-Solyman',
    'category': '',
    'author': 'Solyman',
    'maintainer': 'Solyman',
    'company': 'Solyman',
    'website': 'https://solymanconsulting.com/',
    'depends': ['base','sale','stock','hr','l10n_pe_edi','web','product_unspsc','uom'],
    # 'pre_init_hook': 'pre_init_hook',
    'data': [
        'security/ir.model.access.csv',
        'views/view_picking_form.xml',
        'views/hr_employee_views.xml',
        'views/stock_picking_views.xml',
        'views/res_company_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_view.xml',
        'views/catalog_63_64_views.xml',
        'views/uom_uom_views.xml',
        'views/transportation_reason_other_views.xml',
        'report/custom_header_footer_deliveryslip.xml',
        'report/report_deliveryslip.xml',
        'data/2.1/edi_despatch_advice.xml',
        'data/2.1/edi_signature_despatch_advice.xml',
        'data/department_transportation_data.xml',
        'data/catalog_63_64_data.xml',
        #'report/stock_report_views.xml',
        'views/account_move_views.xml',
        'views/stock_package_type_view.xml',
        'views/stock_quant_views.xml',
        #'views/report_invoice.xml',
        ],
    'installable': True,
    'license': 'AGPL-3',
}